baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 10

  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'Français'
    weight = 20